"use strict";
const CACHE_NAME="win11-simulator-v9.9.4";
const PRECACHE=[
  "./",
  "./index.html",
  "./favicon.svg?v=8.1.0",
  "./manifest.webmanifest?v=8.1.0",
  "./styles/base.css?v=8.1.0",
  "./styles/system-v4.css?v=8.1.0",
  "./styles/system-suite-v5.css?v=8.1.0",
  "./styles/realism-v62.css?v=8.1.0",
  "./styles/app-realism-v63.css?v=8.1.0",
  "./styles/real-files-v640.css?v=8.1.0",
  "./styles/real-clipboard-v650.css?v=8.1.0",
  "./styles/real-content-v660.css?v=8.1.0",
  "./styles/real-platform-v660.css?v=8.1.0",
  "./styles/local-accounts-v670.css?v=8.1.0",
  "./styles/real-device-tools-v680.css?v=8.1.0",
  "./styles/desktop-integration-v700.css?v=8.1.0",
  "./styles/real-folder-mounts-v710.css?v=8.1.0",
  "./styles/edge-internet-v720.css?v=8.1.2",
  "./styles/edge-advanced-v730.css?v=8.1.0",
  "./styles/explorer-pro-v740.css?v=8.1.0",
  "./styles/explorer-navigation-v820.css?v=8.3.0",
  "./styles/explorer-details-v840.css?v=8.4.0",
  "./styles/explorer-context-v850.css?v=8.5.0",
  "./styles/explorer-views-v860.css?v=8.6.0",
  "./styles/explorer-sidebar-v870.css?v=9.3.0",
  "./styles/explorer-command-v880.css?v=8.8.0",
  "./styles/explorer-columns-v890.css?v=8.9.0",
  "./styles/explorer-operations-v900.css?v=9.0.0",
  "./styles/explorer-filesystem-v910.css?v=9.1.0",
  "./styles/window-manager-v750.css?v=8.1.0",
  "./styles/real-device-integration-v760.css?v=8.1.0",
  "./styles/notifications-background-v770.css?v=8.1.0",
  "./styles/settings-security-v780.css?v=8.1.0",
  "./styles/shell-icons-v781.css?v=8.1.0",
  "./styles/system-tray-quick-v790.css?v=8.1.0",
  "./styles/windows-experience-v800.css?v=8.1.0",
  "./styles/start-search-taskbar-v810.css?v=8.1.0",
  "./styles/search-v920.css?v=9.2.0",
  "./styles/explorer-multiwindow-v930.css?v=9.3.0",
  "./styles/explorer-history-v940.css?v=9.4.0",
  "./styles/explorer-recycle-v950.css?v=9.5.0",
  "./styles/explorer-versions-v960.css?v=9.6.0",
  "./styles/taskbar-window-v970.css?v=9.7.0",
  "./styles/settings-personalization-v982.css?v=9.8.2",
  "./styles/taskbar-system-v983.css?v=9.8.3",
  "./styles/settings-explorer-v984.css?v=9.8.4",
  "./styles/resource-monitor-v9841.css?v=9.8.4-hotfix.1",
"./styles/apps-defaults-v985.css?v=9.8.5",
"./styles/storage-v986.css?v=9.8.6",
"./styles/system-health-v987.css?v=9.8.7",
"./styles/app-sessions-v991.css?v=9.9.1",
"./styles/session-restore-v992.css?v=9.9.2",
"./styles/session-recovery-v994.css?v=9.9.4",
  "./src/core/runtime.js?v=9.9.2",
  "./src/features/system-v4.js?v=8.1.0",
  "./src/apps/v5-runtime.js?v=8.1.0",
  "./src/apps/explorer-v5.js?v=9.8.6",
  "./src/apps/settings-v5.js?v=9.8.7",
  "./src/apps/windows-tools.js?v=8.1.0",
  "./src/apps/services.js?v=8.1.0",
  "./src/apps/disk-management.js?v=8.1.0",
  "./src/apps/task-scheduler.js?v=8.1.0",
  "./src/apps/system-info.js?v=8.1.0",
  "./src/apps/resource-monitor.js?v=8.1.0",
  "./src/apps/powershell.js?v=9.9.0",
  "./src/apps/optional-features.js?v=8.1.0",
  "./src/apps/backup-recovery.js?v=8.1.0",
  "./src/apps/sticky-notes.js?v=8.1.0",
  "./src/apps/onedrive.js?v=8.1.0",
  "./src/apps/remote-desktop.js?v=8.1.0",
  "./src/apps/sound-recorder.js?v=8.1.0",
  "./src/apps/get-help.js?v=8.1.0",
  "./src/apps/shell-integration.js?v=9.9.0",
  "./src/apps/search-v5.js?v=8.1.0",
  "./src/features/realism-v62.js?v=8.1.0",
  "./src/features/app-realism-v63.js?v=8.1.0",
  "./src/features/real-files-v640.js?v=9.6.0",
  "./src/features/real-clipboard-v650.js?v=8.1.0",
  "./src/features/real-content-v660.js?v=8.1.0",
  "./src/features/real-platform-v660.js?v=8.1.0",
  "./src/features/local-accounts-v670.js?v=9.9.2",
  "./src/features/real-device-tools-v680.js?v=8.1.0",
  "./src/features/desktop-integration-v700.js?v=9.8.5",
  "./src/features/real-folder-mounts-v710.js?v=8.1.0",
  "./src/features/edge-internet-v720.js?v=8.1.2",
  "./src/features/edge-advanced-v730.js?v=9.8.5",
  "./src/features/explorer-pro-v740.js?v=9.6.0",
  "./src/features/explorer-navigation-v820.js?v=9.8.6",
  "./src/features/explorer-details-v840.js?v=9.8.6",
  "./src/features/explorer-context-v850.js?v=9.1.0",
  "./src/features/explorer-views-v860.js?v=8.6.0",
  "./src/features/explorer-sidebar-v870.js?v=8.7.0",
  "./src/features/explorer-command-v880.js?v=8.8.0",
  "./src/features/explorer-columns-v890.js?v=9.1.0",
  "./src/features/explorer-operations-v900.js?v=9.7.0",
  "./src/features/explorer-filesystem-v910.js?v=9.2.0",
  "./src/features/window-manager-v750.js?v=8.1.0",
  "./src/features/real-device-integration-v760.js?v=8.1.0",
  "./src/features/notifications-background-v770.js?v=9.8.6",
  "./src/features/settings-security-v780.js?v=8.1.0",
  "./src/features/system-tray-quick-v790.js?v=8.1.0",
  "./src/features/windows-experience-v800.js?v=8.1.0",
  "./src/features/start-search-taskbar-v810.js?v=9.3.0",
  "./src/features/search-v920.js?v=9.2.0",
  "./src/features/explorer-multiwindow-v930.js?v=9.3.0",
  "./src/features/explorer-history-v940.js?v=9.5.0",
  "./src/features/explorer-recycle-v950.js?v=9.5.0",
  "./src/features/explorer-versions-v960.js?v=9.6.0",
  "./src/features/taskbar-window-v970.js?v=9.7.0",
  "./src/features/system-bus-v981.js?v=9.8.1",
  "./src/features/settings-core-v981.js?v=9.8.7",
  "./src/features/settings-personalization-v982.js?v=9.8.3",
  "./src/features/taskbar-system-v983.js?v=9.8.3",
  "./src/features/settings-explorer-v984.js?v=9.8.4",
"./src/features/apps-defaults-v985.js?v=9.8.5",
"./src/features/storage-v986.js?v=9.8.6",
"./src/features/system-health-v987.js?v=9.8.7",
"./src/features/shell-intents-v990.js?v=9.9.0",
"./src/features/app-sessions-v991.js?v=9.9.1",
"./src/features/session-restore-v992.js?v=9.9.4",
"./src/features/session-recovery-v994.js?v=9.9.4",
  "./src/workers/auth-crypto-v673.js?v=8.1.0",
  "./src/core/boot.js?v=8.1.0",
  "./icons/icon-192.png",
  "./icons/icon-512.png"
];

self.addEventListener("install",event=>{
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache=>cache.addAll(PRECACHE))
  );
});

self.addEventListener("message",event=>{
  if(event.data?.type==="SKIP_WAITING")self.skipWaiting();
});

self.addEventListener("activate",event=>{
  event.waitUntil(
    caches.keys()
      .then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k))))
      .then(()=>self.clients.claim())
  );
});

self.addEventListener("fetch",event=>{
  const req=event.request;
  if(req.method!=="GET")return;
  const url=new URL(req.url);
  if(url.origin!==self.location.origin)return;

  if(req.mode==="navigate"){
    event.respondWith(
      fetch(req)
        .then(res=>{
          const copy=res.clone();
          caches.open(CACHE_NAME).then(cache=>cache.put("./index.html",copy));
          return res;
        })
        .catch(()=>caches.match("./index.html"))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(cached=>{
      if(cached)return cached;
      return fetch(req).then(res=>{
        if(res&&res.ok){
          const copy=res.clone();
          caches.open(CACHE_NAME).then(cache=>cache.put(req,copy));
        }
        return res;
      });
    })
  );
});
